spring.application.name=java_init
# Banco PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/demo
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create


### Loggin Configuration
spring.profiles.active=dev


logging.level.org.springframework.boot.autoconfigure=ERROR


spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false
