### Loggin Configuration
logging.level.org.springframework=trace


###Types of logging
# Configuração de nível de logging para o Spring Framework
#logging.level.org.springframework=info
# Configuração de nível de logging para o Hibernate
#logging.level.org.hibernate=info
# Configuração de nível de logging para o pacote com.example
#logging.level.com.example=info
# Configuração de nível de logging para o pacote principal da aplicação
#logging.level.com.example.init_java=info
# Configuração de nível de logging para os controllers
#logging.level.com.example.init_java.controller=info
# Configuração de nível de logging para os services
#logging.level.com.example.init_java.service=info
# Configuração de nível de logging para os repositories
#logging.level.com.example.init_java.repository=info
# Configuração de nível de logging para os models
#logging.level.com.example.init_java.model=info
# Configuração de nível de logging específica para a classe User
#logging.level.com.example.init_java.model.User=info

### Outros
#warn
#error
#fatal
#trace
#debug
#info

