POST http://localhost:8080/auth/register
Content-Type: application/json

{
    "name": "malu",
    "email": "malu@gmail.com",
    "password": "123"
}

###
GET http://localhost:8080/users

###
DELETE http://localhost:8080/users/5

###
GET http://localhost:8080/hello

###
POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "email": "malu@gmail.com",
    "password": "123"
}

###
POST http://localhost:8080/auth/logout

###
GET http://localhost:8080/auth/validate

###
POST http://localhost:8080/contacts
Content-Type: application/json

{
  "name": "Joao abreu",
  "phone": "+55 71 95555-4444",
  "email": "joao.abreu@email.com",
  "company": "Marketing Plus",
  "jobTitle": "Especialista em Marketing",
  "address": "Av. Sete de Setembro, 150 - Salvador/BA"
}

###
GET http://localhost:8080/contacts?sortBy=nme&order=asc&page=1&limit=10

###
DELETE http://localhost:8080/contacts/18

### 
PATCH http://localhost:8080/contacts/1
Content-Type: application/json

{
    "name": "Maria Oliveiraaa",
    "jobTitle": null
}

###
GET http://localhost:8080/contacts/filt
